export const HttpStatusCodes = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  REQUEST_TIME_OUT: 408,
  CONFLICT: 409,
  UNSUPPROTED_MEDIA_TYPE: 415,
  INTERNAL_SERVER_ERROR: 500,
} as const

export const MONGOOSE_VALIDATION_ERROR = 'ValidationError'
